### ISSUE TITLE
Catch ConnectionError Exceptions on modules with bad connections.

### ISSUE THREAD

**Issue by dmw109** [dmw109/pyrtma#5]

**Comment by dmw109** [comment]
I think it is fine to catch all ConnectionErrors instead of any specific subclasses. I am not sure that we could recover the connection in any case.

**Comment by jmw182** [comment]
> I think it is fine to catch all ConnectionErrors instead of any specific subclasses. I am not sure that we could recover the connection in any case.

Agreed, I figured we would want to disconnect regardless of the type of disconnect error. I'm just not sure yet if we need to add more try/except blocks to catch connection errors elsewhere, e.g. when sending a message. So far this is the only connection error I've actually seen occur.

**Comment by jmw182** [comment]
> It may be beneficial to have message manager try to send an ack or something periodically to prune any modules that are dead and not sending or subscribed.

Interesting idea but we'd have to think a bit about how to do that properly. Some modules can be idle without anything being wrong, e.g. they pause subscriptions before they stop reading. Our Executive module does this. But I agree it would be good to prune crashed matlab modules that don't disconnect or unsubscribe.

Maybe we can keep track of how many failed messages are sent to each module in a given amount of time, and if some threshold is reached the connection would be dropped.

**Comment by dmw109** [comment]
> > It may be beneficial to have message manager try to send an ack or something periodically to prune any modules that are dead and not sending or subscribed.
> 
> Interesting idea but we'd have to think a bit about how to do that properly. Some modules can be idle without anything being wrong, e.g. they pause subscriptions before they stop reading. Our Executive module does this. But I agree it would be good to prune crashed matlab modules that don't disconnect or unsubscribe.
> 
> Maybe we can keep track of how many failed messages are sent to each module in a given amount of time, and if some threshold is reached the connection would be dropped. This would be good for a new issue/enhancement.

I don't think the module would even need to reply, the fact that message went through and we got no error would indicate the socket is valid. We only need message manager to initiate the write, I believe we would get an error if the module crashed and we tried to write. It probably wouldn't show up as ready to write though from select.

**Comment by jmw182** [comment]
I guess we could get an error if we try to send a message to a module immediately after it disconnects, as a race condition:
1. Module A connects and subscribes to message type sent from module B
2. New iteration of message manager's `run` loop begins
1. Message manager gets `rlist` from select, module A may or may not be in it
2. Message manager gets `wlist` from select, module A is in it
3. Module A disconnects or crashes
4. Message manager receives a message from module B before attempting to read from module A. Attempts to forward message to module A.
5. Connection error may occur when writing to socket

The error that I've actually seen and handled is that after a module disconnects, it still appears in the `rlist` (maybe because it sent the Disconnect message?), but then a connection error occurs when it tries to read it. Since the sockets are shuffled and I've only been doing simple tests with a single client, I suppose the situation above could happen. I can try to test for it.

I would think the way to fix that would be to put a try/except around every socket write, not to send extra ACK messages for this purpose. Since we still use a lot of matlab, I think the most common "crash" is when a matlab module errors out (or is ctrl+c'd) and so matlab returns to the command line but does not close the process or socket. So the socket is still valid but no longer being read. The module would continue to appear in the `wlist` until the buffer is full, and message manager already detects that and starts sending FAILED_MESSAGE and printing 'x's. It would be an improvement to automatically close the socket after a certain number of failed messages are sent in a row, but I'm not sure if there's much value in adding a special ACK message to accomplish that.

**Comment by jmw182** [comment]
I just verified this race condition can happen. Right now, since `process_message` is in the same `try` block, it will be caught in the same `except` block and incorrectly disconnect the sender instead of the receiver. I'll fix this.

**Comment by jmw182** [comment]
Caught and ignored ConnectionErrors when writing to a socket seem to immediately result in a second ConnectionError on the next read, so I think it will be sufficient to put each write in a try block, catch and log and connection errors, but only force a disconnect on the read error.

**Comment by jmw182** [comment]
Fixed in 3e29118. Message manager now seems to be robust to crashing on connection errors on either writes or reads. Errors on writes are logged and ignored, errors on reads are logged and the module is disconnected.

I might add sending a failed message when the error occurs on the write (currently that only happens if module is not in wlist). Otherwise I think this issue can be closed, and pruning inactive modules could be moved to a new issue.

**Comment by jmw182** [comment]
Added the failed_message in aab1f0d5. I'm pretty happy with this. I added a statement to send_failed_message to return early if the type of the failed message is a FailedMessage, to prevent infinite recursion e.g if a logger module crashes.

I also saw that sometimes the error will happen on a write, and then the disconnect signal will be successfully read on the next read WITHOUT an error. So I feel like that's probably good enough justification for only forcing disconnections on failed reads, and not failed writes.

I can open another issue for pruning inactive modules (which generally should not appear in wlist), so I think it's separate from the ConnectionError issue. I'll close this issue.
